Repository marroe01284/NEXUS, pull requests merged in 2024-04, with the labels that each got.

#48 Fix data.json
  data.json
Labels: easy

#50 FIX: fixed link from newuser to questionaire
  js/newuser.js
Labels: enhancement

#57 FIX: Swiping-feature
  css/swipe.css
Labels: css
